### ISSUE TITLE
[RFE] Add optional filter for conditional redirects

### ISSUE THREAD

**Issue by grafuls** [redhat-performance/wppt#29]
Add an optional `filter` field on the yaml structure that would do a conditional redirect based on values from the payload.

Example:
```yaml
gitlab2jira:
  enabled: true
  target_webhook: https://example.com/rest/cb-automation/latest/hooks/{JIRA_WEBHOOK_ID}
  translations:
    data:
      name: '[{payload[project][name]}][{payload[object_kind]}] {payload[object_attributes][title]}'
      description: 'Description: {payload[object_attributes][description]}\nURL:{payload[object_attributes][url]}' 
  filter:
    - equal:
      field: payload[action]
      value: opened
```
